### ISSUE TITLE
Doesn't work on version 1.18.2 pojavlauncher

### ISSUE THREAD

**Issue by ArmaN11123885** [Chocohead/OptiFabric#1616]
java.lang.NoClassDefFoundError: net/fabricmc/tinyremapper/IMappingProvider
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:43)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.tinyremapper.IMappingProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more

**Comment by Dracconis** [comment]
Use Fabric Loader 0.14.25. also next time please do a search to see if your issue has already been solved.

**Comment by ArmaN11123885** [comment]
I even tried it on 0.14.25, but this time it crashes and gives an error -1. I did everything right, I threw it in folder

**Comment by Dracconis** [comment]
> I even tried it on 0.14.25, but this time it crashes and gives an error -1. I did everything right, I threw it in folder

You have to use the Launcher to install the 0.14.25 Fabric Launcher Profile. You dont put the Fabric Launcher jar file in any folder. You use the jar file to install the profile I just mentioned.

**Comment by ArmaN11123885** [comment]
I put the files in a folder and ran it first on 0.14.25 but it didn’t work. Then I launched Minecraft on 0.15.11, it worked, but this is displayed
![Screenshot_20240511_225550](https://github.com/Chocohead/OptiFabric/assets/169547149/fcecb956-4245-4e17-9f38-81607b66ffbf)
![Screenshot_20240511_225340](https://github.com/Chocohead/OptiFabric/assets/169547149/2f3ebd7a-67fe-43b5-bb49-b1cc1385b972)

**Comment by ArmaN11123885** [comment]
If I did something wrong I'm sorry

**Comment by Dracconis** [comment]
Try using the Fabric Loader 0.14.25 Profile in the MC launcher but using the Optifabric 1.13.16 version and Fabric API 0.76.0. Last checked and I could be wrong here but I believe Replay Mod and Optifabric dont work together right now.

**Comment by ArmaN11123885** [comment]
I did as you said and launched Minecraft and everything worked. It turned out that Optifabric conflicts with with mod Blur I removed this mod and everything works with Replay mod. And can you give me some version of the mod Blur which will work at 0.14.25. And thank you so much for your help and advice. I'm really grateful to you

**Comment by Dracconis** [comment]
Unfortunately, the version of Blur that you have been using is the ONLY version for 1.18-1.18.2. So if that is the mod that is conflicting and causing the issue, then you wont be able to use it.

**Comment by ArmaN11123885** [comment]
Are there any replacements for this mod to work with Optifabric?

**Comment by Dracconis** [comment]
Considering I have never bothered or worried about the blur, I wouldn't have any idea.

**Comment by ArmaN11123885** [comment]
OK, thank you

**Comment by Dracconis** [comment]
You're welcome. If this resolves your issue please close the ticket.
