### PR TITLE
Update to 1.16.3 - Base Layer

### PR DESCRIPTION
**Pull request by Wolfieheart**
Hi there Choco,

Did you a small favour and updated the mod for 1.16.3 support. Not sure if everything I have done is correct, but you could probably help work that out!

- Wolfie

### CODE REVIEW

**Comment by Wolfieheart** [comment]
Also to point out this is just the base, as compling this and running it will forcequit Minecraft with the following error:

`Unreported exception thrown!
java.lang.NoSuchMethodError: net.minecraft.class_702.renderParticles(Lnet/minecraft/class_4587;Lnet/minecraft/class_4597$class_4598;Lnet/minecraft/class_765;Lnet/minecraft/class_4184;FLnet/minecraft/class_4604;)V
	at net.minecraft.class_761.method_22710(class_761.java:2006)
	at net.minecraft.class_757.method_3188(class_757.java:1022)
	at net.minecraft.class_757.method_3192(class_757.java:693)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)`

Using the latest OptiFine Preview - seems to be pointing to: net/minecraft/client/util/math/MatrixStack

**Comment by CDAGaming** [comment]
@Wolfst0rm That crash by the way is caused from pre2's changes, as pre1 and 1.16.2s optifine do work fine in 1.16.3

**Comment by CDAGaming** [comment]
it also may likely mean that due to that change this will not likely be compatible for 1.16.2/1.16.1

**Comment by CDAGaming** [comment]
Superseeded by #48

**Comment by Wolfieheart** [comment]
Ah ok good to know. I assumed it was something with mc itself and forgot
about thinking it could be optifine as well. Closing this for now... Please read #48
