### ISSUE TITLE
incompatible with fabric loader 0.12

### ISSUE THREAD

**Issue by ghost** [Chocohead/OptiFabric#408]
trying to launch with optifabric 1.11.20 and fabric loader 0.12.3 generates this error

Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.3!

**Comment by 0xfeeddeadbeef** [comment]
Here's a modified version which works with fabric-loader 0.12.*:

[optifabric-1.11.20.jar](https://storage.googleapis.com/optifabric/optifabric-1.11.20.jar)

[VirusTotal scan results](https://www.virustotal.com/gui/file/69d14126249e858324f662d5d02a5d7f61ba16485174e87f4439ca221c9ff520)

**Comment by qfoxb** [comment]
Another thing you can do is open the jar file with something such as winrar and change 
`"depends": {
    "fabricloader": ">=0.8.0 <0.12.0",` in fabric.mod.json and change 0.12.0 to some random number and it'll load just fine

**Comment by 0xfeeddeadbeef** [comment]
@qfoxb That is exactly what I did here:

> Here's a modified version which works with fabric-loader 0.12.*:
> 
> [optifabric-1.11.20.jar](https://storage.googleapis.com/optifabric/optifabric-1.11.20.jar)
> 
> [VirusTotal scan results](https://www.virustotal.com/gui/file/69d14126249e858324f662d5d02a5d7f61ba16485174e87f4439ca221c9ff520)

**Comment by qfoxb** [comment]
👍

**Comment by Felix0163** [comment]
java.lang.NoSuchMethodError: 'net.fabricmc.loader.game.GameProvider net.fabricmc.loader.FabricLoader.getGameProvider()'
	at me.modmuss50.optifabric.mod.OptifineSetup.getLaunchMinecraftJar(OptifineSetup.java:338)
	at me.modmuss50.optifabric.mod.OptifineSetup.getMinecraftJar(OptifineSetup.java:316)
	at me.modmuss50.optifabric.mod.OptifineSetup.getRuntime(OptifineSetup.java:96)
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:41)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by 0xfeeddeadbeef** [comment]
@Felix0163  OptiFine U H1 is not supported yet. That's a separate issue altogether.

**Comment by ZekerZhayard** [comment]
same as https://github.com/Chocohead/OptiFabric/issues/394
